# Generated by Django 3.2.6 on 2021-10-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='dept',
            field=models.CharField(choices=[('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Electrical', 'Electrical'), ('ComputerScience', 'Computer Science'), ('Electronics&Communication', 'Electronics & Communication'), ('Event', 'Event'), ('CDC', 'CDC')], default='Computer Science', max_length=100),
        ),
    ]
