# Generated by Django 3.2.6 on 2021-12-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_news_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='dept',
            field=models.CharField(choices=[('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Electrical', 'Electrical'), ('ComputerScience', 'Computer Science'), ('Electronics&Communication', 'Electronics & Communication'), ('Event', 'Event'), ('CDC', 'CDC'), ('Sports', 'Sports'), ('Achievement', 'Achievement')], default='Computer Science', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='dept',
            field=models.CharField(choices=[('', 'Department'), ('Not Applicable', 'Not Applicable'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil '), ('Electrical', 'Electrical'), ('Computer Science', 'Computer Science'), ('Electronics & Communication', 'Electronics & Communication')], default='Computer Science', max_length=40),
        ),
    ]
